// Shared mock data for NaturaO prototype
// FR copy, NL placeholders ready to fill

const NATURAO_PRODUCERS = [
  {
    id: 1,
    slug: "ferme-du-peuplier",
    nom: "Ferme du Peuplier",
    pays: "Belgique",
    region: "Brabant wallon",
    specialite: "Maraîchage régénératif",
    accroche: "Une ferme engagée dans une agriculture vivante.",
    image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&q=80",
    hue: 95,
  },
  {
    id: 2,
    slug: "domaine-de-la-vallee",
    nom: "Domaine de la Vallée",
    pays: "France",
    region: "Loire",
    specialite: "Vins nature",
    accroche: "Des vins vivants, travaillés sans intrants.",
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&q=80",
    hue: 40,
  },
  {
    id: 3,
    slug: "fromagerie-van-den-berg",
    nom: "Fromagerie Van den Berg",
    pays: "Belgique",
    region: "Flandre",
    specialite: "Fromages fermiers",
    accroche: "Un affinage patient, au rythme du lait cru.",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=1200&q=80",
    hue: 60,
  },
  {
    id: 4,
    slug: "huilerie-toscana",
    nom: "Huilerie Toscana",
    pays: "Italie",
    region: "Toscane",
    specialite: "Huile d'olive extra-vierge",
    accroche: "Une olive cueillie à la main, pressée à froid.",
    image: "https://images.unsplash.com/photo-1445264718234-a623be589d37?w=1200&q=80",
    hue: 75,
  },
  {
    id: 5,
    slug: "boulangerie-du-vieux-moulin",
    nom: "Boulangerie du Vieux Moulin",
    pays: "Belgique",
    region: "Ardennes",
    specialite: "Pains au levain",
    accroche: "Farines paysannes, fermentations longues.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&q=80",
    hue: 30,
  },
  {
    id: 6,
    slug: "verger-des-hauteurs",
    nom: "Verger des Hauteurs",
    pays: "Belgique",
    region: "Condroz",
    specialite: "Fruits de saison",
    accroche: "Variétés anciennes et cueillette à maturité.",
    image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=1200&q=80",
    hue: 20,
  },
  {
    id: 7,
    slug: "apiculture-des-hetres",
    nom: "Apiculture des Hêtres",
    pays: "Belgique",
    region: "Gaume",
    specialite: "Miels de terroir",
    accroche: "Des ruches posées au plus près de la forêt.",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&q=80",
    hue: 50,
  },
  {
    id: 8,
    slug: "maison-delaforge",
    nom: "Maison Delaforge",
    pays: "France",
    region: "Périgord",
    specialite: "Charcuteries fermières",
    accroche: "Des porcs élevés en plein air, travaillés entiers.",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=1200&q=80",
    hue: 15,
  },
  {
    id: 9,
    slug: "conserverie-du-port",
    nom: "Conserverie du Port",
    pays: "Portugal",
    region: "Algarve",
    specialite: "Conserves de poisson",
    accroche: "Une pêche raisonnée, mise en boîte à la main.",
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=1200&q=80",
    hue: 200,
  },
  {
    id: 10,
    slug: "safran-de-hesbaye",
    nom: "Safran de Hesbaye",
    pays: "Belgique",
    region: "Hesbaye",
    specialite: "Safran et épices",
    accroche: "Une récolte minutieuse, fleur par fleur.",
    image: "https://images.unsplash.com/photo-1513594736550-3f0fe2b2a3f9?w=1200&q=80",
    hue: 25,
  },
  {
    id: 11,
    slug: "brasserie-du-thyle",
    nom: "Brasserie du Thyle",
    pays: "Belgique",
    region: "Brabant wallon",
    specialite: "Bières de fermentation",
    accroche: "Des bières vivantes, brassées en petite quantité.",
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=1200&q=80",
    hue: 35,
  },
  {
    id: 12,
    slug: "chocolaterie-del-monte",
    nom: "Chocolaterie del Monte",
    pays: "Italie",
    region: "Piémont",
    specialite: "Chocolat de cru",
    accroche: "Des fèves tracées, torréfiées avec patience.",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=1200&q=80",
    hue: 10,
  },
];

// Featured producer for the dynamic producer page
const NATURAO_FEATURED_PRODUCER = {
  ...NATURAO_PRODUCERS[0],
  histoire:
    "La Ferme du Peuplier cultive une grande diversité de fruits et légumes selon une approche régénérative, où le sol et la biodiversité sont au cœur du travail. Avec plus de 90 variétés cultivées, la ferme privilégie la diversité et la résilience, afin de proposer des produits savoureux, durables et cohérents avec leur environnement.",
  methode: [
    "Une production maîtrisée",
    "Un savoir-faire précis",
    "Une recherche constante de qualité",
  ],
  engagement:
    "Chaque récolte est le résultat d'un travail précis, guidé par l'observation, l'expérience et une volonté constante d'amélioration.",
  galerie: [
    "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1200&q=80",
    "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&q=80",
    "https://images.unsplash.com/photo-1444858291040-58f756a3bdd6?w=1200&q=80",
    "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=1200&q=80",
  ],
  produitsAssocies: [
    { nom: "Tomates anciennes", categorie: "Légumes", saison: true },
    { nom: "Courges d'hiver", categorie: "Légumes", saison: true },
    { nom: "Herbes aromatiques", categorie: "Aromates", saison: false },
    { nom: "Fraises des bois", categorie: "Fruits", saison: false },
  ],
};

const NATURAO_TAGLINES = [
  "Des producteurs engagés, des produits justes",
  "La qualité avant tout",
  "Le goût du vrai, sans compromis",
  "Sélectionné pour ce que c'est, pas pour ce que ça vend",
  "Des produits sincères, au prix juste",
  "Moins de volume, plus de sens",
];

Object.assign(window, {
  NATURAO_PRODUCERS,
  NATURAO_FEATURED_PRODUCER,
  NATURAO_TAGLINES,
});
